# Automatically run semantic checks, linters, and unit tests

name: Code Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-code:
    runs-on: ubuntu-24.04

    steps:
      # TODO install uv
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv and enable caching
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.5.4"

      - name: Set up Python with uv
        run: uv python install

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache mhlib
        id: cache-mhlib
        uses: actions/cache@v4
        with:
          path: |
            MHLib_v3.1.0.0_64bit
          key: ${{ runner.os }}-mhlib

      - name: Install mhlib if not cached
        if: steps.cache-mhlib.outputs.cache-hit != 'true'
        run: ./install_mhlib.sh

      - name: Install more dependencies
        run: |
          ./bin/install-dependencies.bash

      - name: Run check script
        run: |
          ./bin/check.bash

      - name: Clean up uv cache
        run: uv cache prune --ci
